=== Windower/Lumoria/data/schemas/installable.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://manifests.lumoria.dev/1/schemas/installable.json",
  "title": "Lumoria installable manifest",
  "type": "object",
  "required": ["id", "name"],
  "properties": {
    "$schema": { "type": "string" },
    "id": { "$ref": "defs.json#/$defs/nonempty_string" },
    "name": { "type": "string" },
    "label": { "type": "string" },
    "icon": { "type": "string" },
    "skip_versions": {
      "type": "array",
      "items": { "type": "string" }
    },
    "features": {
      "type": "array",
      "items": { "type": "string" }
    },
    "downloads": {
      "type": "array",
      "items": { "$ref": "defs.json#/$defs/download" }
    },
    "steps": {
      "type": "array",
      "items": { "$ref": "defs.json#/$defs/step" }
    },
    "actions": {
      "type": "array",
      "items": { "$ref": "defs.json#/$defs/action" }
    },
    "remote_manifest_actions": {
      "type": "array",
      "items": { "$ref": "defs.json#/$defs/remote_manifest_action" }
    },
    "env": {
      "type": "array",
      "items": { "$ref": "defs.json#/$defs/env_rule" }
    },
    "reinstallable": { "type": "boolean" },
    "wineboot_mscoree": { "type": "string" },
    "variables": {
      "type": "object",
      "additionalProperties": { "$ref": "defs.json#/$defs/variable" }
    },
    "entrypoints": {
      "type": "array",
      "items": { "$ref": "defs.json#/$defs/entrypoint" }
    },
    "redists": {
      "type": "array",
      "items": { "type": "string" }
    },
    "recommended": { "type": "boolean" },
    "support": { "$ref": "defs.json#/$defs/support" },
    "messages": { "$ref": "defs.json#/$defs/messages" },
    "links": { "$ref": "defs.json#/$defs/links" },
    "metadata": { "$ref": "defs.json#/$defs/metadata" }
  }
}

=== Windower/Lumoria/data/specs/redists/segoeui-noto.json
{
  "id": "segoeui-noto",
  "name": "Segoe UI Noto Sans Aliases",
  "redists": [
    "notosans"
  ],
  "steps": [
    {
      "type": "font_replacement",
      "description": "Register Segoe UI font replacements",
      "font_registrations": [
        "Segoe UI|Noto Sans",
        "Segoe UI Light|Noto Sans Light",
        "Segoe UI Semibold|Noto Sans Bold"
      ]
    }
  ]
}

=== Windower/Lumoria/data/specs/redists/constantia.json
{
  "id": "constantia",
  "name": "Constantia",
  "downloads": [
    {
      "id": "pptviewer",
      "url": "https://share.lumoria.dev/redists/pptfonts/PowerPointViewer.exe",
      "dest": "${var.CACHE_REDIST}/pptfonts/PowerPointViewer.exe",
      "sha256": "249473568eba7a1e4f95498acba594e0f42e6581add4dead70c1dfb908a09423"
    }
  ],
  "steps": [
    {
      "type": "cabextract",
      "description": "Extract ppviewer.cab",
      "src": "${var.CACHE_REDIST}/pptfonts/PowerPointViewer.exe",
      "args": [
        "ppviewer.cab"
      ],
      "dst": "${var.CACHE_REDIST}/pptfonts/ppviewer.cab"
    },
    {
      "type": "fonts",
      "description": "Install Constantia",
      "dst": "${var.FONTS}",
      "args": [
        "${var.CACHE_REDIST}/pptfonts/ppviewer.cab"
      ],
      "font_registrations": [
        "constan.ttf|Constantia",
        "constanb.ttf|Constantia Bold",
        "constani.ttf|Constantia Italic",
        "constanz.ttf|Constantia Bold Italic"
      ],
      "when": {
        "not": {
          "file_exists": "${var.FONTS}/constan.ttf"
        }
      }
    }
  ]
}

=== Windower/Lumoria/data/manifests/redists/ipamona.json
{
  "$schema": "https://manifests.lumoria.dev/1/schemas/redist.json",
  "id": "ipamona",
  "name": "IPAMona Fonts",
  "downloads": [
    {
      "id": "ipamona_archive",
      "url": "https://share.lumoria.dev/redists/ipamona/opfc-ModuleHP-1.1.1_withIPAMonaFonts-1.0.8.tar.gz",
      "dest": "${var.CACHE_REDIST}/ipamona/opfc-ModuleHP-1.1.1_withIPAMonaFonts-1.0.8.tar.gz",
      "sha256": "ab77beea3b051abf606cd8cd3badf6cb24141ef145c60f508fcfef1e3852bb9d"
    }
  ],
  "steps": [
    {
      "type": "fonts",
      "description": "Install IPAMona fonts",
      "dst": "${var.FONTS}",
      "args": [
        "${var.CACHE_REDIST}/ipamona/opfc-ModuleHP-1.1.1_withIPAMonaFonts-1.0.8.tar.gz"
      ],
      "font_registrations": [
        "ipagui-mona.ttf|IPAMonaUIGothic",
        "ipag-mona.ttf|IPAMonaGothic",
        "ipagp-mona.ttf|IPAMonaPGothic",
        "ipam-mona.ttf|IPAMonaMincho",
        "ipamp-mona.ttf|IPAMonaPMincho"
      ],
      "when": {
        "not": {
          "file_exists": "${var.FONTS}/ipag-mona.ttf"
        }
      }
    }
  ]
}

=== Windower/Lumoria/data/specs/redists/baekmuk.json
{
  "id": "baekmuk",
  "name": "Baekmuk Fonts",
  "downloads": [
    {
      "id": "baekmuk_archive",
      "url": "https://deb.debian.org/debian/pool/main/f/fonts-baekmuk/fonts-baekmuk_2.2.orig.tar.gz",
      "dest": "${var.CACHE_REDIST}/baekmuk/fonts-baekmuk_2.2.orig.tar.gz",
      "sha256": "08ab7dffb55d5887cc942ce370f5e33b756a55fbb4eaf0b90f244070e8d51882"
    }
  ],
  "steps": [
    {
      "type": "fonts",
      "description": "Install Baekmuk fonts",
      "dst": "${var.FONTS}",
      "args": [
        "${var.CACHE_REDIST}/baekmuk/fonts-baekmuk_2.2.orig.tar.gz"
      ],
      "font_registrations": [
        "batang.ttf|Baekmuk Batang",
        "gulim.ttf|Baekmuk Gulim",
        "dotum.ttf|Baekmuk Dotum",
        "hline.ttf|Baekmuk Headline"
      ],
      "when": {
        "not": {
          "file_exists": "${var.FONTS}/batang.ttf"
        }
      }
    }
  ]
}

=== Windower/Lumoria/data/specs/redists/unifont.json
{
  "id": "unifont",
  "name": "GNU Unifont",
  "downloads": [
    {
      "id": "unifont_ttf",
      "url": "https://unifoundry.com/pub/unifont/unifont-13.0.06/font-builds/unifont-13.0.06.ttf",
      "dest": "${var.CACHE_REDIST}/unifont/unifont-13.0.06.ttf",
      "sha256": "d73c0425811ffd366b0d1973e9338bac26fe7cf085760a12e10c61241915e742"
    }
  ],
  "steps": [
    {
      "type": "fonts",
      "description": "Install GNU Unifont",
      "dst": "${var.FONTS}",
      "args": [
        "${var.CACHE_REDIST}/unifont/unifont-13.0.06.ttf"
      ],
      "font_registrations": [
        "unifont-13.0.06.ttf|Unifont"
      ],
      "when": {
        "not": {
          "file_exists": "${var.FONTS}/unifont-13.0.06.ttf"
        }
      }
    }
  ]
}

=== Windower/Lumoria/data/manifests/redists/d3dcompiler_46.json
{
  "$schema": "https://manifests.lumoria.dev/1/schemas/redist.json",
  "id": "d3dcompiler_46",
  "name": "d3dcompiler_46",
  "downloads": [
    {
      "id": "d3dcompiler_46_x86",
      "url": "https://download.microsoft.com/download/F/1/3/F1300C9C-A120-4341-90DF-8A52509B23AC/standalonesdk/Installers/2630bae9681db6a9f6722366f47d055c.cab",
      "dest": "${var.CACHE_REDIST}/d3dcompiler_46/d3dcompiler_46_x86.cab",
      "sha256": "359ff931beaeb24f0493099baceddfdb27876617dc5057e86742de652faf1d38"
    },
    {
      "id": "d3dcompiler_46_x64",
      "url": "https://download.microsoft.com/download/F/1/3/F1300C9C-A120-4341-90DF-8A52509B23AC/standalonesdk/Installers/61d57a7a82309cd161a854a6f4619e52.cab",
      "dest": "${var.CACHE_REDIST}/d3dcompiler_46/d3dcompiler_46_x64.cab",
      "sha256": "e3e05076784fed086203eff7c5ff4b406bbd2e649fd938eb73c1b7d05f49cdfc",
      "when": {
        "var": {
          "ARCH": "win64"
        }
      }
    }
  ],
  "steps": [
    {
      "type": "dll_override",
      "description": "Set d3dcompiler_46 to native",
      "command": "d3dcompiler_46",
      "mode": "native"
    },
    {
      "type": "cabextract",
      "description": "Extract d3dcompiler_46.dll (x86 -> syswow64)",
      "src": "${var.CACHE_REDIST}/d3dcompiler_46/d3dcompiler_46_x86.cab",
      "args": [
        "fil47ed91e900f4b9d9659b66a211b57c39"
      ],
      "dst": "${var.SYSWOW64}/d3dcompiler_46.dll",
      "when": {
        "var": {
          "ARCH": "win64"
        }
      }
    },
    {
      "type": "cabextract",
      "description": "Extract d3dcompiler_46.dll (x86 -> system32)",
      "src": "${var.CACHE_REDIST}/d3dcompiler_46/d3dcompiler_46_x86.cab",
      "args": [
        "fil47ed91e900f4b9d9659b66a211b57c39"
      ],
      "dst": "${var.SYSTEM32}/d3dcompiler_46.dll",
      "when": {
        "var": {
          "ARCH": "win32"
        }
      }
    },
    {
      "type": "cabextract",
      "description": "Extract d3dcompiler_46.dll (x64 -> system32)",
      "src": "${var.CACHE_REDIST}/d3dcompiler_46/d3dcompiler_46_x64.cab",
      "args": [
        "fil8c20206095817436f8df4a711faee5b7"
      ],
      "dst": "${var.SYSTEM32}/d3dcompiler_46.dll",
      "when": {
        "var": {
          "ARCH": "win64"
        }
      }
    }
  ]
}

=== Windower/Lumoria/data/specs/redists/dotnet8.json
{
  "id": "dotnet8",
  "name": ".NET Runtime 8.0",
  "variables": {
    "DOTNET_X86_ROOT": {
      "default": "drive_c/Program Files/dotnet",
      "rules": [
        {
          "value": "drive_c/Program Files (x86)/dotnet",
          "when": {
            "var": {
              "ARCH": "win64"
            }
          }
        }
      ]
    },
    "DOTNET_X64_ROOT": "drive_c/Program Files/dotnet"
  },
  "downloads": [
    {
      "id": "dotnet8_x86",
      "url": "https://download.visualstudio.microsoft.com/download/pr/3210417e-ab32-4d14-a152-1ad9a2fcfdd2/da097cee5aa85bd79b6d593e3866fb7f/dotnet-runtime-8.0.12-win-x86.exe",
      "dest": "${var.CACHE_REDIST}/dotnet8/dotnet-runtime-8.0.12-win-x86.exe",
      "sha256": "eb0d8f39fa2dbb4ff3ff72ad325b6030773df875ab509824ea18c87a368985fa"
    },
    {
      "id": "dotnet8_x64",
      "url": "https://download.visualstudio.microsoft.com/download/pr/136f4593-e3cd-4d52-bc25-579cdf46e80c/8b98c1347293b48c56c3a68d72f586a1/dotnet-runtime-8.0.12-win-x64.exe",
      "dest": "${var.CACHE_REDIST}/dotnet8/dotnet-runtime-8.0.12-win-x64.exe",
      "sha256": "a7c394e6ee4e8104d7a01f78103700052cc504370941b7f620e3aa5afbbc61df",
      "when": {
        "var": {
          "ARCH": "win64"
        }
      }
    }
  ],
  "steps": [
    {
      "type": "wineexec",
      "description": "Install .NET Runtime 8.0 (x86)",
      "command": "${var.CACHE_REDIST}/dotnet8/dotnet-runtime-8.0.12-win-x86.exe",
      "args": [
        "/quiet"
      ],
      "working_dir": "${var.CACHE_REDIST}/dotnet8",
      "verify_paths": [
        "${var.PREFIX}/${var.DOTNET_X86_ROOT}/dotnet.exe"
      ]
    },
    {
      "type": "wineexec",
      "description": "Install .NET Runtime 8.0 (x64)",
      "command": "${var.CACHE_REDIST}/dotnet8/dotnet-runtime-8.0.12-win-x64.exe",
      "args": [
        "/quiet"
      ],
      "working_dir": "${var.CACHE_REDIST}/dotnet8",
      "verify_paths": [
        "${var.PREFIX}/${var.DOTNET_X64_ROOT}/dotnet.exe"
      ],
      "when": {
        "var": {
          "ARCH": "win64"
        }
      }
    }
  ]
}

=== Windower/Lumoria/data/specs/redists/meiryo.json
{
  "id": "meiryo",
  "name": "Meiryo",
  "downloads": [
    {
      "id": "pptviewer",
      "url": "https://share.lumoria.dev/redists/pptfonts/PowerPointViewer.exe",
      "dest": "${var.CACHE_REDIST}/pptfonts/PowerPointViewer.exe",
      "sha256": "249473568eba7a1e4f95498acba594e0f42e6581add4dead70c1dfb908a09423"
    }
  ],
  "steps": [
    {
      "type": "cabextract",
      "description": "Extract ppviewer.cab",
      "src": "${var.CACHE_REDIST}/pptfonts/PowerPointViewer.exe",
      "args": [
        "ppviewer.cab"
      ],
      "dst": "${var.CACHE_REDIST}/pptfonts/ppviewer.cab"
    },
    {
      "type": "fonts",
      "description": "Install Meiryo",
      "dst": "${var.FONTS}",
      "args": [
        "${var.CACHE_REDIST}/pptfonts/ppviewer.cab"
      ],
      "font_registrations": [
        "meiryo.ttc|Meiryo",
        "meiryob.ttc|Meiryo Bold"
      ],
      "when": {
        "not": {
          "file_exists": "${var.FONTS}/meiryo.ttc"
        }
      }
    }
  ]
}
